---
title: "Can We Really Trust the 10-Day Forecast?"
author: "Alex Baburnic, Nate Hansen, & David Vanegas"
date: "4/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Forecasts
SLC_Forecast <- read.csv("forecast_data/SLC_forecast.csv")
KSL_Forecast <- read.csv("forecast_data/KSL_forecast.csv")
NY_Forecast <- read.csv("forecast_data/NY_forecast.csv")
CHI_Forecast <- read.csv("forecast_data/CHI_forecast.csv")
ATX_Forecast <- read.csv("forecast_data/ATX_forecast.csv")
SF_Forecast <- read.csv("forecast_data/SF_forecast.csv")
#Actual temperatures
SLC_Actual <- read.csv("actualTemp_data/SLC_ActualTemp.csv")
NY_Actual <- read.csv("actualTemp_data/NY_ActualTemp.csv")
CH_Actual <- read.csv("actualTemp_data/CH_ActualTemp.csv")
ATX_Actual <- read.csv("actualTemp_data/ATX_ActualTemp.csv")
SF_Actual <- read.csv("actualTemp_data/SF_ActualTemp.csv")
```

## Introduction

Anyone who has sat through a rainy picnic knows by hard experience that the reliability of the weather forecast has measurable impact on one's life. In the modern age of technology and the "Internet of Things", humans have devised algorithms to provide themselves peace-of-mind and certainty. Yet, as they eat their soggy sandwiches under a nearby pergola, people wonder why the weather forecast said it would be clear when they planned the picnic a week ago. Is it common for the forecast to be so inconsistent, or did they just get anomalously unlucky? Does the local weather station or the national one provide more accurate forecast data? Sometimes the forecast calls for relatively warm days within a week, and when the days approach, the forecast has gotten much cooler or warmer. In the Salt Lake Valley, the temperature often changes sporadically near the spring equinox, referred to by the locals as "Utah weather". Is this oscillation really unique to Utah at this time of year? Are there other cities in the United States that seem to have more reliable forecasts? The authors will attempt to answer some of these questions with confidence using statistical analysis of weather data gathered from local and national forecasts.

#### Importance of Studying Weather Station Reliability
Reliable weather forecasts would bring greater certainty to the conditions from events as small as the family picnic to as large as community firework shows or rocket launches. Although gathering data about the reliability of the forecast will not inherently improve its reliability, this information can help people make decisions about where to live. Knowing the comparative reliability of the forecast for various cities can help organizations plan large national events and assess the risk of unpredictability. Data comparing local forecasts to national forecasts will help people determine which forecast to trust more when they seem to be disparate. In a broader sense, some believe that modern extreme weather patterns are a direct result of climate change, and therefore climate change damages weather predictability. Based on these topics of value, the following questions can be operationalized:

1) In Salt Lake City, is the 7th day of the local KSL weather forecast more or less accurate than the 7th day of the forecast provided by the U. S. National Weather Service?

2) Of the cities Salt Lake City, UT; Austin, TX; San Francisco, CA; New York, NY; and Chicago, IL; which city's 10th forecast day is, on average, closest to the actual temperature that day?

3) Does the city with the "most accurate" forecast according to question 2 also have the least variability in temperature over the month of March?

***4) Do the cities with the "less accurate" forecast according to question 2 also exhibit the greatest change in average temperature or temperature variance since 80 years ago?***

*the above header line can be deleted to make this all one part of the intro.*
*List out the main topics and sections of the report to the reader, then transition to the next section. Remember, the professor wants these reports to "flow" together like a story.*

#### Methodology

To gather data that answers our question, we will use a variety of sources. Data for national forecasts will be gathered from The Weather Channel. Local Salt Lake City forecasts will be gathered from KSL Weather. Historical true high and low temperatures will be gathered from NOAA, where the stations gathering measurements will be located at the metropolis centers where the forecast is being calculated. Historic data will be gathered at only one station in each city.

The forecast sources do not seem to disclose how often they update their forecasts, so we had to devise a good way to collect a large sample of forecast predictions for each day. We considered collecting a random sample, but it is a little unrealistic to manually record the forecast at random times during the day.



## Data Collection

Display here the results of the gathered data.

Limitations:
- Forecast data was collected systematically, sampled infrequently
- Forecast sample size is relatively large, but not enough to overcome skewness
- We don't know which stations weather.com uses
- 

NOAA:
- Actual Temps 3/2/2022-4/7/2022 for SLC, Austin, TX; SF, CA; CHI, IL; NY, NY;
***-Historical data from same cities during same time***

#### Data Observations
This is an optional subsection, but it may make the document flow better. Here make some very general observations regarding the data, such as very obvious trends or outliers that may or may not be taken into consideration (and explain why).

## Data Analysis

Make meaningful analysis of the data with respect to the question of the topic. Unlike the previous subsection, go much more into detail here. Explain what certain data trends and values relate to the question and possibly make inferences that could be understood outside of statistics (you can think of the starting paragraph discussion on the Assignment 3 Canvas page).

1) In Salt Lake City, is the 7th day of the local KSL weather forecast more or less accurate than the 7th day of the forecast provided by the U. S. National Weather Service?

2) Of the cities Salt Lake City, UT; Austin, TX; San Francisco, CA; New York, NY; and Chicago, IL; which city's 10th forecast day is, on average, closest to the actual temperature that day?

3) Does the city with the "most accurate" forecast according to question 2 also have the least variability in temperature over the given time period?

4) Do the cities with the "less accurate" forecast according to question 2 also exhibit the greatest change in average temperature or temperature variance since 80 years ago?

## Conclusion

Summarize thoughts from analysis, as well as the data collection process, to answer the questions of the topic.